name: Deploy Middleman site to Staging

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: staging
  cancel-in-progress: true

env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}

jobs:
  deploy-staging:
    if: ${{ vars.ENVIRONMENT == 'staging'}}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Echo build environment
        run: echo "$ENVIRONMENT"
      - name: Build with Middleman
        run: bundle exec middleman build -e $ENVIRONMENT
        env:
          BASE_URL: ${{ steps.pages.outputs.base_url }}
          NO_CONTRACTS: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
